name: badrap-deploy
description: Deploy containers to GKE
inputs:
  container_repository:
    description: Container repository
    required: true
  container_tag:
    description: Container tag
    required: true
  cluster_zone:
    description: Cluster zone
    required: true
  cluster_name:
    description: Cluster name
    required: true
  secrets_path:
    description: Secrets path
    required: true
  helm_release:
    description: Helm release name
    required: true
  helm_namespace:
    description: Helm release namespace
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        curl -L -s https://github.com/getsops/sops/releases/download/v3.10.2/sops-v3.10.2.linux.amd64 > "${GITHUB_ACTION_PATH}/sops"
        echo "79b0f844237bd4b0446e4dc884dbc1765fc7dedc3968f743d5949c6f2e701739 ${GITHUB_ACTION_PATH}/sops" | sha256sum --check
        chmod u+x "${GITHUB_ACTION_PATH}/sops"
      shell: bash
    - run: |
        curl -L -s https://get.helm.sh/helm-v3.18.4-linux-amd64.tar.gz > "${GITHUB_ACTION_PATH}/helm.tar.gz"
        echo "f8180838c23d7c7d797b208861fecb591d9ce1690d8704ed1e4cb8e2add966c1 ${GITHUB_ACTION_PATH}/helm.tar.gz" | sha256sum --check
        tar xf "${GITHUB_ACTION_PATH}/helm.tar.gz" -C "${GITHUB_ACTION_PATH}"
      shell: bash
    - uses: google-github-actions/get-gke-credentials@8e574c49425fa7efed1e74650a449bfa6a23308a # v2.3.4
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.cluster_zone }}
        use_dns_based_endpoint: 'true'
    - env:
        CONTAINER_REPOSITORY: ${{ inputs.container_repository }}
        CONTAINER_TAG: ${{ inputs.container_tag }}
        SECRETS_PATH: ${{ inputs.secrets_path }}
        HELM_RELEASE: ${{ inputs.helm_release }}
        HELM_NAMESPACE: ${{ inputs.helm_namespace }}
      run: |
        "${GITHUB_ACTION_PATH}/sops" -d "${SECRETS_PATH}" | "${GITHUB_ACTION_PATH}/linux-amd64/helm" upgrade "${HELM_RELEASE}" helm-chart --install --atomic --namespace "${HELM_NAMESPACE}" --create-namespace --values - --set image.repository="${CONTAINER_REPOSITORY}" --set image.tag="${CONTAINER_TAG}"
      shell: bash
