name: badrap-deploy
description: Deploy containers to GKE
inputs:
  container_repository:
    description: Container repository
    required: true
  container_tag:
    description: Container tag
    required: true
  cluster_zone:
    description: Cluster zone
    required: true
  cluster_name:
    description: Cluster name
    required: true
  secrets_path:
    description: Secrets path
    required: true
  helm_release:
    description: Helm release name
    required: true
  helm_namespace:
    description: Helm release namespace
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        curl -L -s https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux > "${GITHUB_ACTION_PATH}/sops"
        chmod u+x "${GITHUB_ACTION_PATH}/sops"
      shell: bash
    - run: |
        curl -L -s https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz > "${GITHUB_ACTION_PATH}/helm.tar.gz"
        tar xf "${GITHUB_ACTION_PATH}/helm.tar.gz" -C "${GITHUB_ACTION_PATH}"
      shell: bash
    - uses: google-github-actions/get-gke-credentials@v1.0.2
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.cluster_zone }}
    - env:
        CONTAINER_REPOSITORY: ${{ inputs.container_repository }}
        CONTAINER_TAG: ${{ inputs.container_tag }}
        SECRETS_PATH: ${{ inputs.secrets_path }}
        HELM_RELEASE: ${{ inputs.helm_release }}
        HELM_NAMESPACE: ${{ inputs.helm_namespace }}
      run: |
        "${GITHUB_ACTION_PATH}/sops" -d "${SECRETS_PATH}" | "${GITHUB_ACTION_PATH}/linux-amd64/helm" upgrade "${HELM_RELEASE}" helm-chart --install --atomic --namespace "${HELM_NAMESPACE}" --create-namespace --values - --set image.repository="${CONTAINER_REPOSITORY}" --set image.tag="${CONTAINER_TAG}"
      shell: bash
