name: badrap-deploy
description: Deploy containers to GKE
inputs:
  container_repository:
    description: Container repository
    required: true
  container_tag:
    description: Container tag
    required: true
  cluster_zone:
    description: Cluster zone
    required: true
  cluster_name:
    description: Cluster name
    required: true
  secrets_path:
    description: Secrets path
    required: true
  helm_release:
    description: Helm release name
    required: true
  helm_namespace:
    description: Helm release namespace
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        curl -L -s https://github.com/getsops/sops/releases/download/v3.11.0/sops-v3.11.0.linux.amd64 > "${GITHUB_ACTION_PATH}/sops"
        echo "775f1384d55decfad228e7196a3f683791914f92a473f78fc47700531c29dfef ${GITHUB_ACTION_PATH}/sops" | sha256sum --check
        chmod u+x "${GITHUB_ACTION_PATH}/sops"
      shell: bash
    - run: |
        curl -L -s https://get.helm.sh/helm-v4.0.0-linux-amd64.tar.gz > "${GITHUB_ACTION_PATH}/helm.tar.gz"
        echo "c77e9e7c1cc96e066bd240d190d1beed9a6b08060b2043ef0862c4f865eca08f ${GITHUB_ACTION_PATH}/helm.tar.gz" | sha256sum --check
        tar xf "${GITHUB_ACTION_PATH}/helm.tar.gz" -C "${GITHUB_ACTION_PATH}"
      shell: bash
    - uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395 # v3.0.0
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.cluster_zone }}
        use_dns_based_endpoint: 'true'
    - env:
        CONTAINER_REPOSITORY: ${{ inputs.container_repository }}
        CONTAINER_TAG: ${{ inputs.container_tag }}
        SECRETS_PATH: ${{ inputs.secrets_path }}
        HELM_RELEASE: ${{ inputs.helm_release }}
        HELM_NAMESPACE: ${{ inputs.helm_namespace }}
      run: |
        "${GITHUB_ACTION_PATH}/sops" -d "${SECRETS_PATH}" | "${GITHUB_ACTION_PATH}/linux-amd64/helm" upgrade "${HELM_RELEASE}" helm-chart --install --rollback-on-failure --namespace "${HELM_NAMESPACE}" --create-namespace --values - --set image.repository="${CONTAINER_REPOSITORY}" --set image.tag="${CONTAINER_TAG}"
      shell: bash
