name: badrap-deploy
description: Deploy containers to GKE
inputs:
  gcloud_container_repository:
    description: GCloud container repository
    required: true
  cluster_zone:
    description: Cluster zone
    required: true
  cluster_name:
    description: Cluster name
    required: true
  secrets_path:
    description: Secrets path
    required: true
  helm_release:
    description: Helm release name
    required: true
  helm_namespace:
    description: Helm release namespace
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        curl https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux > "${GITHUB_ACTION_PATH}/sops"
        chmod u+x "${GITHUB_ACTION_PATH}/sops"
      shell: bash
    - run: |
        curl https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz > "${GITHUB_ACTION_PATH}/helm.tar.gz"
        tar xfv "${GITHUB_ACTION_PATH}/helm.tar.gz" -C "${GITHUB_ACTION_PATH}"
      shell: bash
    # - env:
    #     GCLOUD_CONTAINER_REPOSITORY: ${{ inputs.gcloud_container_repository }}
    #     CLUSTER_ZONE: ${{ inputs.cluster_zone }}
    #     CLUSTER_NAME: ${{ inputs.cluster_name }}
    #     SECRETS_PATH: ${{ inputs.secrets_path }}
    #     HELM_RELEASE: ${{ inputs.helm_release }}
    #     HELM_NAMESPACE: ${{ inputs.helm_namespace }}
    #   run: |
    #     gcloud --quiet container clusters get-credentials -z "${CLUSTER_ZONE}" "${CLUSTER_NAME}"
    #     "${GITHUB_ACTION_PATH}/sops" -d "${SECRETS_PATH}" | "${GITHUB_ACTION_PATH}/linux-amd64/helm" upgrade "${INPUT_HELM_RELEASE}" helm-chart --install --atomic --namespace "${INPUT_HELM_NAMESPACE}" --create-namespace --values - --set image.repository="${GCLOUD_CONTAINER_REPOSITORY}" --set image.tag="${GITHUB_SHA}"
