name: badrap-deploy
description: Deploy containers to GKE
inputs:
  gcloud_project:
    description: GCloud project
    required: true
  gcloud_service_key:
    description: GCloud service key
    required: true
  gcloud_container_repository:
    description: GCloud container repository
    required: true
  cluster_zone:
    description: Cluster zone
    required: true
  cluster_name:
    description: Cluster name
    required: true
  secrets_path:
    description: Secrets path
    required: true
  helm_release:
    description: Helm release name
    required: true
  helm_namespace:
    description: Helm release namespace
    required: true
runs:
  using: docker
  image: 'badrap/actions@latest'
