name: badrap-push
description: Push a container to GCloud
inputs:
  gcloud_project:
    description: GCloud project
    required: true
  gcloud_service_key:
    description: GCloud service key
    required: true
  gcloud_container_repository:
    description: GCloud container repository
    required: true
  input_image:
    description: Input image
    required: true
outputs:
  output_image:
    description: Output image
runs:
  using: "docker"
  image: "docker://ghcr.io/badrap/github-actions:latest"
  entrypoint: "/root/push/entrypoint.sh"
